### ISSUE TITLE
Implement css selection

### ISSUE THREAD

**Issue by NelDav** [tfachmann/MdCollab#15]

**Comment by tfachmann** [comment]
What exactly is this issue?

Is it the same as #26, or already done in #14 ?

**Comment by NelDav** [comment]
I am confused. I think it is the same as #26.

**Comment by tfachmann** [comment]
Both opened by yourself :)

**Comment by NelDav** [comment]
Yes but I already have a branch to close them. I will create the PR in a few minutes. :D
